'use client';

import React, { useState, useEffect, useRef } from 'react';
import { IconX, IconCopy, IconCheck, IconFileText } from '@tabler/icons-react';
import { ChatMessage } from '../VideoRoom';

interface MomOverlayProps {
  roomName: string;
  messages: ChatMessage[];
  topicNotes: string;
  onClose: () => void;
}

export default function MomOverlay({
  roomName,
  messages,
  topicNotes,
  onClose,
}: MomOverlayProps) {
  
  const [copied, setCopied] = useState(false);
  const containerRef = useRef<HTMLDivElement>(null);

  // Close on Escape press
  useEffect(() => {
    const handleKeyDown = (e: KeyboardEvent) => {
      if (e.key === 'Escape') onClose();
    };
    window.addEventListener('keydown', handleKeyDown);
    return () => window.removeEventListener('keydown', handleKeyDown);
  }, [onClose]);

  // Close on outside click
  useEffect(() => {
    function handleClickOutside(event: MouseEvent) {
      if (containerRef.current && !containerRef.current.contains(event.target as Node)) {
        onClose();
      }
    }
    document.addEventListener('mousedown', handleClickOutside);
    return () => document.removeEventListener('mousedown', handleClickOutside);
  }, [onClose]);

  // Generate structured Minutes of Meeting text
  const generateMoMText = () => {
    const dateStr = new Date().toLocaleDateString(undefined, { 
      weekday: 'long', 
      year: 'numeric', 
      month: 'long', 
      day: 'numeric' 
    });

    const chatSection = messages.length > 0
      ? messages.map(m => {
          const time = new Date(m.timestamp).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' });
          return `[${time}] ${m.senderName}: "${m.text}"`;
        }).join('\n')
      : 'No chat messages were recorded during this session.';

    const topicSection = topicNotes.trim()
      ? `"${topicNotes.trim()}"`
      : 'Class Session in Progress';

    return `==================================================
        OPENGRAPES LIVE — CLASSROOM SUMMARY
==================================================
Session ID:   ${roomName.toUpperCase()}
Date:         ${dateStr}
Class Topic:  ${topicSection}

--------------------------------------------------
1. CLASS AGENDA & TOPICS COVERED
--------------------------------------------------
* Active Lesson Focus: ${topicSection}
* Collaborative digital whiteboard used during session.
* Screen sharing and live video discussions active.

--------------------------------------------------
2. CLASSROOM CHAT LOG TRANSCRIPT
--------------------------------------------------
${chatSection}

--------------------------------------------------
3. GENERAL DECISIONS & FOLLOW-UP ITEMS
--------------------------------------------------
* Review whiteboard drawings exported to PDF notes.
* Complete exercises and follow-up reading assigned by the teacher.
* Direct message classroom logs and notes uploaded automatically.

Generated by OpenGrapes AI Assistant.
==================================================`;
  };

  const handleCopy = () => {
    navigator.clipboard.writeText(generateMoMText());
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="fixed inset-0 bg-shell/80 backdrop-blur-md z-50 flex items-center justify-center p-4 md:p-6 animate-in fade-in duration-200">
      
      {/* Overlay box card */}
      <div 
        ref={containerRef}
        className="bg-surface border border-border rounded-2xl max-w-2xl w-full max-h-[85vh] flex flex-col p-6 shadow-2xl relative text-text font-sans"
      >
        
        {/* Header */}
        <div className="flex items-center justify-between pb-3 border-b border-border/40 select-none">
          <div className="flex items-center gap-2">
            <IconFileText className="w-5 h-5 text-accent" />
            <h3 className="text-sm font-bold uppercase tracking-wider text-white">Class Minutes (MoM)</h3>
          </div>
          <button 
            onClick={onClose}
            className="w-7 h-7 rounded-lg hover:bg-surface-hi flex items-center justify-center text-text-muted hover:text-white transition-colors cursor-pointer"
          >
            <IconX className="w-4 h-4" />
          </button>
        </div>

        {/* Info Note */}
        <p className="text-[10px] text-text-muted mt-3 select-none leading-relaxed">
          Below is a compiled summary of the live classroom notes, topic discussions, and chat log transcript. Copy the content to your clipboard to save or share.
        </p>

        {/* Scrollable Text Summary Container */}
        <div className="flex-1 min-h-0 overflow-y-auto mt-4 mb-5 p-4 bg-shell/65 border border-border/70 rounded-xl text-xs font-mono whitespace-pre-wrap text-text-muted select-text leading-relaxed scrollbar-thin">
          {generateMoMText()}
        </div>

        {/* Action Controls footer */}
        <div className="flex items-center justify-end gap-3 pt-3 border-t border-border/40 select-none">
          <button
            onClick={onClose}
            className="px-4 py-2 border border-border bg-transparent hover:bg-surface-hi text-xs font-bold text-text-muted hover:text-white rounded-lg transition-colors cursor-pointer"
          >
            Close
          </button>
          
          <button
            onClick={handleCopy}
            className={`px-4 py-2 rounded-lg text-xs font-bold flex items-center gap-1.5 transition-all shadow-md cursor-pointer ${
              copied 
                ? 'bg-success text-white shadow-success/15' 
                : 'bg-accent hover:bg-accent-hi text-white shadow-accent/15'
            }`}
          >
            {copied ? (
              <>
                <IconCheck className="w-4 h-4" />
                <span>Copied!</span>
              </>
            ) : (
              <>
                <IconCopy className="w-4 h-4" />
                <span>Copy Summary</span>
              </>
            )}
          </button>
        </div>

      </div>

    </div>
  );
}
